
 language: node_js


 node_js: 
    - "10"

 cache: npm

 # 邮件通知，这里配置不管成功或是失败都通知
 notifications:
  email:false
     

 # 安装环境
 install:
 - npm install -g gitbook-cli
 - gitbook install

 # gitbook生成静态文件
 script:
 - gitbook build

 
 after_script:
 - cd _book
 - git init
 - git remote add origin https://${REF}
 - git config user.name "Sylar"
 - git config user.email "swlfigo@gmail.com"
 - git add .
 - git commit -m "Update GitBook By TravisCI With Build $TRAVIS_BUILD_NUMBER"
 - git push --force --quiet "https://${TOKEN}@${REF}" master:gh-pages

 branches:
  only:
    - master


 env:
  global:
 # Github Pages 
    - REF=github.com/swlfigo/technologyArticles.git # 设置 github 地址